### ISSUE TITLE
Optimizations, again

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#1670]
Having done some optimizations in #882, the changes to `ArraySequence` (ceylon/ceylon.language#312) mean that there's some more work to do.
- [x] We should try to show that `List`'s `Iterator` is more efficient now that it avoids boxing.
- [x] The static optimization for `ArraySequence` (which was always of dubious worth) is definitely broken: Let's take that code out.
- [x] The optimization for `Tuple` (which worked only because the Java impl of Tuple extended `ArraySequence`) is definitely broken: We should either fix it or take it out.
- [x] We should additionally have a static optimization for iteration over a `String`.
- [x] The static optimization of Array (`for (int in intArray.iterable)`) should still be working, but let's check.
- [x] The existing static optimizations for `Range` (including `..` and `:`) should be unaffected.
- [x] The dynamic optimization (i.e. the default transformation of `for` which did different things depending on the runtime type) is broken because the `ArraySequence` optimization is broken. I guess we need to take that out too.
- [x] As per #1680 optimize `is Element null` to that we can efficiently use `List.getFromFirst()` for the `Iterator` of `List`.
- [ ] Fix ceylon/ceylon.language#478 and understand the consequences for optimized `Tuple` iteration.
- [x] Update loop optimizations for ceylon/ceylon-spec#451 (new `Enumerable`/`Range`) and ceylon/ceylon.language#484 (`SizedRange`)
